# -*- coding: utf-8 -*-
"""dbc-codegen 插件 — DBC → C 代码生成（cantools generate 风格）
功能：
- DBC → C 头文件 + 源文件
- 每报文生成 pack_<msg>() / unpack_<msg>() 函数
- Intel / Motorola 双字节序、signed / factor / offset 处理
- 值表宏（#define <MSG>_<SIG>_<VAL>）
- 命名风格选项（snake_case 保持原名 / 全大写）
- 纯离线工具
依赖: pip install PyQt6
"""

import re
import time

import sin
import dbcparse


def _safe_name(name, style):
    s = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if style == "upper":
        return s.upper()
    return s


def _extract_fn(sig, body_var):
    """生成 raw 提取表达式（简化：按字节拼接）"""
    if sig.little_endian:
        # Intel：start_bit 是 LSB 的 DBC 位号
        lines = []
        n_bytes = (sig.bit_length + 7) // 8
        start_byte = sig.start_bit // 8
        start_off = sig.start_bit % 8
        expr_parts = []
        for i in range(n_bytes):
            byte_i = start_byte + i
            if i == 0 and start_off:
                expr_parts.append("((uint64_t)(%s[%d] >> %d) & 0x%02XULL)"
                                  % (body_var, byte_i, start_off,
                                     min(0xFF, (0xFF >> start_off)) if sig.bit_length - i * 8 >= 8 - start_off else ((1 << min(8, sig.bit_length)) - 1) & 0xFF))
            else:
                expr_parts.append("((uint64_t)%s[%d] << %d)" % (body_var, byte_i, i * 8 - (start_off if i else 0)))
        return " | ".join(expr_parts) if expr_parts else "0"
    else:
        # Motorola：start_bit 是 MSB 的位号
        return "/* motorola */ 0"


def generate_c(db, style="keep"):
    """生成 (header_text, source_text)"""
    guard = "DBC_GEN_H"
    h = ["/* Auto-generated by sin dbc-codegen from DBC: %s */" % (db.path or ""),
         "/* Time: %s */" % time.strftime("%Y-%m-%d %H:%M:%S"),
         "#ifndef %s" % guard, "#define %s" % guard, "",
         "#include <stdint.h>", "#include <stddef.h>", ""]
    c = ["/* Auto-generated by sin dbc-codegen */",
         '#include "dbc_gen.h"', ""]

    msg_defs = []
    for cid, m in db.messages.items():
        msg_name = _safe_name(m.name, style)
        struct_name = "%s_t" % msg_name
        # 结构体
        h.append("/* %s (0x%X, DLC %d, sender %s, cycle %dms) */" % (
            m.name, cid, m.dlc, m.sender, m.cycle_time))
        if m.comment:
            h.append("/* %s */" % m.comment)
        h.append("typedef struct {")
        for s in m.signals:
            t = ("int%d_t" % s.bit_length) if s.is_signed else ("uint%d_t" % s.bit_length)
            if s.bit_length > 64:
                t = "uint64_t"
            comment = " /* %s, %g+%g, %s */" % (s.name, s.factor, s.offset, s.unit) if s.unit or s.factor != 1 else ""
            h.append("    %s %s;%s" % (t, _safe_name(s.name, style), comment))
        h.append("} %s;" % struct_name)
        h.append("")
        msg_defs.append((m, msg_name, struct_name, cid))

        # 值表宏
        for s in m.signals:
            if s.value_table:
                for val, desc in sorted(s.value_table.items()):
                    h.append("#define %s_%s_%d %d  /* %s */" % (
                        msg_name.upper(), _safe_name(s.name, "upper"), val, val, desc))
        h.append("")

    # pack/unpack 原型与实现
    for m, msg_name, struct_name, cid in msg_defs:
        h.append("size_t pack_%s(const %s *s, uint8_t *buf, size_t len);" % (msg_name, struct_name))
        h.append("int unpack_%s(const uint8_t *buf, size_t len, %s *s);" % (msg_name, struct_name))

        # pack 实现
        c.append("size_t pack_%s(const %s *s, uint8_t *buf, size_t len)" % (msg_name, struct_name))
        c.append("{")
        c.append("    if (len < %d) return 0;" % max(m.dlc, 8))
        c.append("    memset(buf, 0, %d);" % max(m.dlc, 8))
        for s in m.signals:
            sn = _safe_name(s.name, style)
            raw_field = "s->%s" % sn
            # factor/offset 逆转：raw = (phys - offset) / factor
            if s.factor != 1.0 or s.offset != 0.0:
                c.append("    { int64_t raw = (int64_t)((%s - (%g)) / %g);"
                         % (raw_field, s.offset, s.factor))
                raw_field = "raw"
            c.append("    /* %s: start %d, len %d, %s */" % (
                s.name, s.start_bit, s.bit_length,
                "intel" if s.little_endian else "motorola"))
            if s.little_endian:
                for bi in range((s.bit_length + 7) // 8):
                    shift = bi * 8
                    mask = 0xFF if s.bit_length - shift >= 8 else ((1 << (s.bit_length - shift)) - 1)
                    byte_index = (s.start_bit + shift) // 8
                    c.append("    buf[%d] |= (uint8_t)((%s >> %d) & 0x%02X);"
                             % (byte_index, raw_field, shift, mask))
            else:
                # Motorola（简化线性填充）
                byte = s.start_bit // 8
                bit = s.start_bit % 8
                for i in range(s.bit_length - 1, -1, -1):
                    if (raw_field, i) == (raw_field, 0) and s.bit_length == 1:
                        c.append("    if (%s) buf[%d] |= 0x%02X;" % (raw_field, byte, 1 << (7 - bit)))
                    else:
                        c.append("    if ((%s >> %d) & 1) buf[%d] |= 0x%02X;"
                                 % (raw_field, i, byte, 1 << (7 - bit)))
                    bit += 1
                    if bit == 8:
                        bit = 0
                        byte += 1
            if s.factor != 1.0 or s.offset != 0.0:
                c.append("    }")
        c.append("    return %d;" % max(m.dlc, 8))
        c.append("}")
        c.append("")

        # unpack 实现
        c.append("int unpack_%s(const uint8_t *buf, size_t len, %s *s)" % (msg_name, struct_name))
        c.append("{")
        c.append("    if (len < %d) return -1;" % max(m.dlc, 8))
        for s in m.signals:
            sn = _safe_name(s.name, style)
            c.append("    { uint64_t raw = 0;")
            if s.little_endian:
                for bi in range((s.bit_length + 7) // 8):
                    byte_index = (s.start_bit + bi * 8) // 8
                    c.append("    raw |= ((uint64_t)buf[%d]) << %d;" % (byte_index, bi * 8))
            else:
                byte = s.start_bit // 8
                bit = s.start_bit % 8
                c.append("    /* motorola */")
                for i in range(s.bit_length):
                    c.append("    raw = (raw << 1) | ((buf[%d] >> %d) & 1);" % (byte, 7 - bit))
                    bit += 1
                    if bit == 8:
                        bit = 0
                        byte += 1
            # 符号扩展
            if s.is_signed and s.bit_length < 64:
                c.append("    if (raw & (1ULL << %d)) raw |= ~((1ULL << %d) - 1);"
                         % (s.bit_length - 1, s.bit_length))
            if s.factor != 1.0 or s.offset != 0.0:
                c.append("    s->%s = (%s)((double)raw * %g + %g);" % (sn, "int64_t" if s.is_signed else "uint64_t", s.factor, s.offset))
            else:
                c.append("    s->%s = (%s)raw;" % (sn, "int64_t" if s.is_signed else "uint64_t"))
            c.append("    }")
        c.append("    return 0;")
        c.append("}")
        c.append("")

    h.append("")
    h.append("#endif /* %s */" % guard)
    return "\n".join(h), "\n".join(c)


def activate(context):
    try:
        from PyQt6.QtWidgets import (
            QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton,
            QTreeWidget, QTreeWidgetItem, QFileDialog, QMessageBox,
            QHeaderView, QComboBox
        )
    except ImportError:
        sin.output.append("DBC 代码生成插件需要 PyQt6: pip install PyQt6")
        return

    db = {"file": None}
    generated = {"h": "", "c": ""}

    win = sin.ui.create_window("DBC C 代码生成器")
    win.resize(940, 600)

    central = QWidget()
    win.setCentralWidget(central)
    layout = QVBoxLayout(central)

    top = QHBoxLayout()
    load_btn = QPushButton("加载 DBC…")
    style_label = QLabel("命名风格:")
    style_combo = QComboBox()
    style_combo.addItems(["保持原名 (snake_case)", "全大写 (UPPER_CASE)"])
    gen_btn = QPushButton("生成代码")
    save_btn = QPushButton("保存 .h/.c…")
    top.addWidget(load_btn)
    top.addWidget(style_label)
    top.addWidget(style_combo)
    top.addWidget(gen_btn)
    top.addStretch(1)
    top.addWidget(save_btn)
    layout.addLayout(top)

    label = QLabel("未加载")
    label.setStyleSheet("color:#888;")
    layout.addWidget(label)

    tree = QTreeWidget()
    tree.setHeaderLabels(["报文", "ID", "信号数", "将生成函数"])
    tree.setAlternatingRowColors(True)
    th = tree.header()
    th.setSectionResizeMode(QHeaderView.ResizeMode.ResizeToContents)
    layout.addWidget(tree, 1)

    preview = __import__("PyQt6.QtWidgets", fromlist=["QTextEdit"]).QTextEdit()
    preview.setReadOnly(True)
    layout.addWidget(preview, 1)

    def _on_load():
        path, _ = QFileDialog.getOpenFileName(win, "加载 DBC", "", "DBC 文件 (*.dbc)")
        if not path:
            return
        d = dbcparse.parse_file(path)
        if not d.messages:
            QMessageBox.warning(win, "加载失败", "无报文定义")
            return
        db["file"] = d
        label.setText("已加载 %s（%d 报文）" % (path.split("\\")[-1], len(d.messages)))
        label.setStyleSheet("color:#2e7d32;")
        tree.clear()
        for cid, m in d.messages.items():
            tree.addTopLevelItem(QTreeWidgetItem([
                m.name, "0x%X" % cid, str(len(m.signals)),
                "pack_%s / unpack_%s" % (m.name, m.name)]))

    def _on_gen():
        if not db["file"]:
            QMessageBox.information(win, "提示", "请先加载 DBC")
            return
        style = "upper" if style_combo.currentIndex() == 1 else "keep"
        h, c = generate_c(db["file"], style)
        generated["h"], generated["c"] = h, c
        preview.setPlainText(h[:4000] + ("\n... (见保存文件)" if len(h) > 4000 else ""))
        QMessageBox.information(win, "生成完成",
                                "已生成 %d 字节头文件 + %d 字节源文件"
                                % (len(h), len(c)))

    def _on_save():
        if not generated["h"]:
            QMessageBox.information(win, "提示", "请先生成代码")
            return
        path, _ = QFileDialog.getSaveFileName(win, "保存头文件", "dbc_gen.h",
                                              "C 头文件 (*.h)")
        if not path:
            return
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(generated["h"])
            c_path = path.rsplit(".", 1)[0] + ".c"
            with open(c_path, "w", encoding="utf-8") as f:
                f.write(generated["c"])
            QMessageBox.information(win, "保存成功", "已保存:\n%s\n%s" % (path, c_path))
        except OSError as e:
            QMessageBox.warning(win, "保存失败", str(e))

    def _on_open_cmd():
        win.show()
        win.raise_()
        win.activateWindow()

    context.register_command("dbcCodegen.open", _on_open_cmd, "数据库: DBC 代码生成")

    load_btn.clicked.connect(_on_load)
    gen_btn.clicked.connect(_on_gen)
    save_btn.clicked.connect(_on_save)

    win.show()
    sin.output.append("DBC 代码生成插件已加载（pack/unpack C 代码，离线工具）")


def deactivate():
    sin.output.append("DBC 代码生成插件已停用")
