# -*- coding: utf-8 -*-
"""C pack/unpack codegen (ported from dbc-codegen)."""

from __future__ import annotations

import os
import re
import time


def _safe_name(name: str, style: str) -> str:
    s = re.sub(r"[^0-9a-zA-Z_]", "_", name)
    if s and s[0].isdigit():
        s = "_" + s
    if style == "upper":
        return s.upper()
    return s


def _c_int_type(bit_length: int, is_signed: bool) -> str:
    if bit_length <= 8:
        width = 8
    elif bit_length <= 16:
        width = 16
    elif bit_length <= 32:
        width = 32
    else:
        width = 64
    return ("int%d_t" if is_signed else "uint%d_t") % width


def _field_type(sig) -> str:
    if sig.factor != 1.0 or sig.offset != 0.0:
        return "double"
    return _c_int_type(min(sig.bit_length, 64), sig.is_signed)


def _emit_extract_raw(lines: list, sig, indent: str = "    ") -> None:
    lines.append("%suint64_t raw = 0;" % indent)
    if sig.little_endian:
        lines.append("%s{" % indent)
        lines.append("%s    unsigned i;" % indent)
        lines.append("%s    for (i = 0; i < %du; ++i) {" % (indent, sig.bit_length))
        lines.append("%s        unsigned bit = %du + i;" % (indent, sig.start_bit))
        lines.append("%s        if ((buf[bit >> 3] >> (7 - (bit & 7))) & 1u)" % indent)
        lines.append("%s            raw |= (uint64_t)1 << i;" % indent)
        lines.append("%s    }" % indent)
        lines.append("%s}" % indent)
    else:
        lines.append("%s{" % indent)
        lines.append("%s    unsigned byte = %du;" % (indent, sig.start_bit >> 3))
        lines.append("%s    unsigned bit = %du;" % (indent, sig.start_bit & 7))
        lines.append("%s    unsigned i;" % indent)
        lines.append("%s    for (i = 0; i < %du; ++i) {" % (indent, sig.bit_length))
        lines.append("%s        raw <<= 1;" % indent)
        lines.append("%s        if ((buf[byte] >> (7 - bit)) & 1u) raw |= 1u;" % indent)
        lines.append("%s        if (++bit == 8u) { bit = 0; ++byte; }" % indent)
        lines.append("%s    }" % indent)
        lines.append("%s}" % indent)
    if sig.is_signed and 0 < sig.bit_length < 64:
        lines.append(
            "%sif (raw & (1ULL << %d)) raw |= ~((1ULL << %d) - 1ULL);"
            % (indent, sig.bit_length - 1, sig.bit_length)
        )


def _emit_insert_raw(lines: list, sig, raw_expr: str, indent: str = "    ") -> None:
    if sig.little_endian:
        lines.append("%s{" % indent)
        lines.append("%s    unsigned i;" % indent)
        lines.append("%s    for (i = 0; i < %du; ++i) {" % (indent, sig.bit_length))
        lines.append("%s        if ((%s >> i) & 1u) {" % (indent, raw_expr))
        lines.append("%s            unsigned bit = %du + i;" % (indent, sig.start_bit))
        lines.append(
            "%s            buf[bit >> 3] |= (uint8_t)(1u << (7 - (bit & 7)));" % indent
        )
        lines.append("%s        }" % indent)
        lines.append("%s    }" % indent)
        lines.append("%s}" % indent)
    else:
        lines.append("%s{" % indent)
        lines.append("%s    unsigned byte = %du;" % (indent, sig.start_bit >> 3))
        lines.append("%s    unsigned bit = %du;" % (indent, sig.start_bit & 7))
        lines.append("%s    int i;" % indent)
        lines.append(
            "%s    for (i = %d; i >= 0; --i) {" % (indent, sig.bit_length - 1)
        )
        lines.append("%s        if ((%s >> i) & 1u)" % (indent, raw_expr))
        lines.append(
            "%s            buf[byte] |= (uint8_t)(1u << (7 - bit));" % indent
        )
        lines.append("%s        if (++bit == 8u) { bit = 0; ++byte; }" % indent)
        lines.append("%s    }" % indent)
        lines.append("%s}" % indent)


def generate_c(db, style: str = "keep") -> tuple:
    """Return (header_text, source_text)."""
    guard = "DBC_GEN_H"
    src_name = os.path.basename(db.path or "dbc")
    h = [
        "/* Auto-generated by openbus DBC Studio from: %s */" % src_name,
        "/* Time: %s */" % time.strftime("%Y-%m-%d %H:%M:%S"),
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    c = [
        "/* Auto-generated by openbus DBC Studio */",
        '#include "dbc_gen.h"',
        "#include <string.h>",
        "",
    ]

    msg_defs = []
    for cid, m in db.messages.items():
        msg_name = _safe_name(m.name, style)
        struct_name = "%s_t" % msg_name
        h.append(
            "/* %s (0x%X, DLC %d, sender %s, cycle %dms) */"
            % (m.name, cid, m.dlc, m.sender, m.cycle_time)
        )
        if m.comment:
            h.append("/* %s */" % m.comment.replace("*/", "* /"))
        h.append("typedef struct {")
        for s in m.signals:
            ft = _field_type(s)
            comment = " /* %s %g+%g %s %s */" % (
                s.name,
                s.factor,
                s.offset,
                s.unit or "",
                "intel" if s.little_endian else "motorola",
            )
            h.append("    %s %s;%s" % (ft, _safe_name(s.name, style), comment))
        h.append("} %s;" % struct_name)
        h.append("")

        for s in m.signals:
            if not s.value_table:
                continue
            for val, desc in sorted(s.value_table.items()):
                h.append(
                    "#define %s_%s_%d %d  /* %s */"
                    % (
                        msg_name.upper(),
                        _safe_name(s.name, "upper"),
                        val,
                        val,
                        str(desc).replace("*/", "* /"),
                    )
                )
        h.append("")
        msg_defs.append((m, msg_name, struct_name, cid))

    for m, msg_name, struct_name, cid in msg_defs:
        dlc = max(int(m.dlc), 1)
        h.append(
            "size_t pack_%s(const %s *s, uint8_t *buf, size_t len);"
            % (msg_name, struct_name)
        )
        h.append(
            "int unpack_%s(const uint8_t *buf, size_t len, %s *s);"
            % (msg_name, struct_name)
        )
        h.append("")

        c.append(
            "size_t pack_%s(const %s *s, uint8_t *buf, size_t len)"
            % (msg_name, struct_name)
        )
        c.append("{")
        c.append("    if (!s || !buf || len < %du) return 0;" % dlc)
        c.append("    memset(buf, 0, %du);" % dlc)
        for s in m.signals:
            sn = _safe_name(s.name, style)
            c.append(
                "    /* %s: start %d len %d %s */"
                % (
                    s.name,
                    s.start_bit,
                    s.bit_length,
                    "intel" if s.little_endian else "motorola",
                )
            )
            if s.factor != 1.0 or s.offset != 0.0:
                c.append("    {")
                c.append(
                    "        int64_t raw = (int64_t)((s->%s - (%g)) / (%g));"
                    % (sn, s.offset, s.factor if s.factor else 1.0)
                )
                _emit_insert_raw(c, s, "raw", "        ")
                c.append("    }")
            else:
                c.append("    {")
                c.append("        uint64_t raw = (uint64_t)s->%s;" % sn)
                _emit_insert_raw(c, s, "raw", "        ")
                c.append("    }")
        c.append("    return %du;" % dlc)
        c.append("}")
        c.append("")

        c.append(
            "int unpack_%s(const uint8_t *buf, size_t len, %s *s)"
            % (msg_name, struct_name)
        )
        c.append("{")
        c.append("    if (!s || !buf || len < %du) return -1;" % dlc)
        for s in m.signals:
            sn = _safe_name(s.name, style)
            ft = _field_type(s)
            c.append("    {")
            _emit_extract_raw(c, s, "        ")
            if s.factor != 1.0 or s.offset != 0.0:
                c.append(
                    "        s->%s = (%s)((double)(int64_t)raw * %g + %g);"
                    % (sn, ft, s.factor, s.offset)
                )
            else:
                c.append("        s->%s = (%s)raw;" % (sn, ft))
            c.append("    }")
        c.append("    return 0;")
        c.append("}")
        c.append("")

    h.append("#endif /* %s */" % guard)
    return "\n".join(h) + "\n", "\n".join(c) + "\n"
