# -*- coding: utf-8 -*-
"""Signal matrix export (ported from dbc-exporter).

Supported interchange formats (stdlib only):
  CSV, Excel CSV (UTF-8 BOM), TSV, JSON, YAML, XML, Markdown, HTML.
"""

from __future__ import annotations

import csv
import html as html_mod
import json
import os
import time
from typing import Any, List, Optional, Tuple


# id, label, extension, filter, description (VS Code–style format picker)
FORMATS: List[Tuple[str, str, str, str, str]] = [
    ("csv", "CSV", ".csv", "CSV (*.csv)",
     "Comma-separated signal matrix — spreadsheets, scripts, CI diffs"),
    ("excel-csv", "Excel CSV", ".csv", "CSV UTF-8 (*.csv)",
     "UTF-8 BOM CSV — opens cleanly in Microsoft Excel / WPS"),
    ("tsv", "TSV", ".tsv", "TSV (*.tsv)",
     "Tab-separated — paste into Excel / Google Sheets without quoting pain"),
    ("json", "JSON", ".json", "JSON (*.json)",
     "Structured tree (messages → signals) for tooling and APIs"),
    ("yaml", "YAML", ".yaml", "YAML (*.yaml *.yml)",
     "Human-readable tree — docs, configs, review in PRs"),
    ("xml", "XML", ".xml", "XML (*.xml)",
     "Simple signal-matrix XML for legacy pipelines"),
    ("markdown", "Markdown", ".md", "Markdown (*.md)",
     "Readable tables for README / Confluence / VS Code preview"),
    ("html", "HTML", ".html", "HTML (*.html *.htm)",
     "Styled report — open in browser or attach to reviews"),
]


def _val_table_str(vt: dict) -> str:
    if not vt:
        return ""
    return "; ".join("%d=%s" % (k, v) for k, v in sorted(vt.items()))


def _cell_str(v: Any) -> str:
    if v is None:
        return ""
    return str(v)


def build_matrix_rows(db, opts: dict):
    headers = [
        "message", "id", "dlc", "sender", "cycle_ms", "signal",
        "start_bit", "length", "byte_order", "signed", "factor", "offset",
    ]
    if opts.get("minmax"):
        headers += ["min", "max"]
    headers.append("unit")
    if opts.get("nodes"):
        headers.append("receivers")
    if opts.get("values"):
        headers.append("value_table")
    if opts.get("comment"):
        headers.append("comment")

    rows = []
    for cid, m in db.messages.items():
        for s in m.signals:
            row = [
                m.name, "0x%X" % cid, m.dlc, m.sender, m.cycle_time, s.name,
                s.start_bit, s.bit_length,
                "Intel" if s.little_endian else "Motorola",
                "signed" if s.is_signed else "unsigned",
                s.factor, s.offset,
            ]
            if opts.get("minmax"):
                row += [s.minimum, s.maximum]
            row.append(s.unit)
            if opts.get("nodes"):
                row.append(" ".join(s.receivers))
            if opts.get("values"):
                row.append(_val_table_str(s.value_table))
            if opts.get("comment"):
                row.append(s.comment or "")
            rows.append(row)
    return headers, rows


def build_json(db, opts: dict) -> dict:
    data = {"version": db.version, "nodes": list(db.nodes), "messages": []}
    for cid, m in db.messages.items():
        msg = {
            "id": cid,
            "name": m.name,
            "dlc": m.dlc,
            "sender": m.sender,
            "cycle_time": m.cycle_time,
            "signals": [],
        }
        if opts.get("comment"):
            msg["comment"] = m.comment or ""
        for s in m.signals:
            sig = {
                "name": s.name,
                "start_bit": s.start_bit,
                "bit_length": s.bit_length,
                "byte_order": "intel" if s.little_endian else "motorola",
                "signed": s.is_signed,
                "factor": s.factor,
                "offset": s.offset,
                "unit": s.unit,
            }
            if opts.get("minmax"):
                sig["min"] = s.minimum
                sig["max"] = s.maximum
            if opts.get("nodes"):
                sig["receivers"] = list(s.receivers)
            if opts.get("values") and s.value_table:
                sig["values"] = {str(k): v for k, v in s.value_table.items()}
            if opts.get("comment") and s.comment:
                sig["comment"] = s.comment
            msg["signals"].append(sig)
        data["messages"].append(msg)
    return data


def _yaml_escape(s: str) -> str:
    if s is None:
        return '""'
    text = str(s)
    if text == "" or any(c in text for c in ":#{}[]&*!|>'\"%@`\n\t") or text.strip() != text:
        return json.dumps(text, ensure_ascii=False)
    return text


def build_yaml(db, opts: dict) -> str:
    """Minimal YAML emitter (no PyYAML dependency)."""
    lines = [
        "# DBC signal matrix — generated by OpenBus DBC Studio",
        "version: %s" % _yaml_escape(db.version or ""),
        "nodes:",
    ]
    for n in db.nodes:
        lines.append("  - %s" % _yaml_escape(n))
    lines.append("messages:")
    for cid, m in db.messages.items():
        lines.append("  - id: %d" % cid)
        lines.append("    name: %s" % _yaml_escape(m.name))
        lines.append("    dlc: %d" % m.dlc)
        lines.append("    sender: %s" % _yaml_escape(m.sender or ""))
        lines.append("    cycle_ms: %s" % m.cycle_time)
        if opts.get("comment") and m.comment:
            lines.append("    comment: %s" % _yaml_escape(m.comment))
        lines.append("    signals:")
        for s in m.signals:
            lines.append("      - name: %s" % _yaml_escape(s.name))
            lines.append("        start_bit: %d" % s.start_bit)
            lines.append("        length: %d" % s.bit_length)
            lines.append(
                "        byte_order: %s"
                % ("intel" if s.little_endian else "motorola"))
            lines.append("        signed: %s" % ("true" if s.is_signed else "false"))
            lines.append("        factor: %s" % s.factor)
            lines.append("        offset: %s" % s.offset)
            lines.append("        unit: %s" % _yaml_escape(s.unit or ""))
            if opts.get("minmax"):
                lines.append("        min: %s" % s.minimum)
                lines.append("        max: %s" % s.maximum)
            if opts.get("nodes") and s.receivers:
                lines.append("        receivers:")
                for r in s.receivers:
                    lines.append("          - %s" % _yaml_escape(r))
            if opts.get("values") and s.value_table:
                lines.append("        values:")
                for k, v in sorted(s.value_table.items()):
                    lines.append("          %s: %s" % (k, _yaml_escape(v)))
            if opts.get("comment") and s.comment:
                lines.append("        comment: %s" % _yaml_escape(s.comment))
    return "\n".join(lines) + "\n"


def write_xml(path: str, db, opts: dict) -> None:
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<dbcMatrix>",
        "  <meta version=\"%s\" messages=\"%d\" generated=\"%s\"/>"
        % (
            html_mod.escape(db.version or ""),
            len(db.messages),
            time.strftime("%Y-%m-%dT%H:%M:%S"),
        ),
        "  <nodes>",
    ]
    for n in db.nodes:
        parts.append("    <node name=\"%s\"/>" % html_mod.escape(n))
    parts.append("  </nodes>")
    parts.append("  <messages>")
    for cid, m in db.messages.items():
        parts.append(
            "    <message id=\"0x%X\" name=\"%s\" dlc=\"%d\" sender=\"%s\" cycle_ms=\"%s\">"
            % (
                cid,
                html_mod.escape(m.name),
                m.dlc,
                html_mod.escape(m.sender or ""),
                m.cycle_time,
            )
        )
        if opts.get("comment") and m.comment:
            parts.append(
                "      <comment>%s</comment>" % html_mod.escape(m.comment))
        for s in m.signals:
            attrs = [
                'name="%s"' % html_mod.escape(s.name),
                'start_bit="%d"' % s.start_bit,
                'length="%d"' % s.bit_length,
                'byte_order="%s"' % ("intel" if s.little_endian else "motorola"),
                'signed="%s"' % ("true" if s.is_signed else "false"),
                'factor="%s"' % s.factor,
                'offset="%s"' % s.offset,
                'unit="%s"' % html_mod.escape(s.unit or ""),
            ]
            if opts.get("minmax"):
                attrs += ['min="%s"' % s.minimum, 'max="%s"' % s.maximum]
            parts.append("      <signal %s>" % " ".join(attrs))
            if opts.get("nodes") and s.receivers:
                for r in s.receivers:
                    parts.append(
                        "        <receiver name=\"%s\"/>"
                        % html_mod.escape(r))
            if opts.get("values") and s.value_table:
                for k, v in sorted(s.value_table.items()):
                    parts.append(
                        "        <value raw=\"%s\">%s</value>"
                        % (k, html_mod.escape(str(v))))
            if opts.get("comment") and s.comment:
                parts.append(
                    "        <comment>%s</comment>"
                    % html_mod.escape(s.comment))
            parts.append("      </signal>")
        parts.append("    </message>")
    parts.append("  </messages>")
    parts.append("</dbcMatrix>")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")


def write_markdown(path: str, db, opts: dict) -> None:
    headers, rows = build_matrix_rows(db, opts)
    lines = [
        "# DBC Signal Matrix",
        "",
        "- Generated: `%s`" % time.strftime("%Y-%m-%d %H:%M:%S"),
        "- Messages: **%d**" % len(db.messages),
        "- Signals: **%d**" % len(rows),
        "- Source: `%s`" % (os.path.basename(db.path or "") or "—"),
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        cells = []
        for c in row:
            text = _cell_str(c).replace("|", "\\|").replace("\n", " ")
            cells.append(text)
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def write_delimited(
        path: str, db, opts: dict, *, delimiter: str, excel_bom: bool = False
) -> None:
    headers, rows = build_matrix_rows(db, opts)
    encoding = "utf-8-sig" if excel_bom else "utf-8"
    with open(path, "w", encoding=encoding, newline="") as f:
        writer = csv.writer(f, delimiter=delimiter, lineterminator="\n")
        writer.writerow(headers)
        for row in rows:
            writer.writerow([_cell_str(c) for c in row])


def write_json(path: str, db, opts: dict) -> None:
    data = build_json(db, opts)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def write_yaml(path: str, db, opts: dict) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(build_yaml(db, opts))


def write_html(path: str, db, opts: dict) -> None:
    parts = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'>",
        "<title>DBC Signal Matrix</title>",
        "<style>",
        "body{font-family:Segoe UI,system-ui,sans-serif;margin:24px;color:#263238;}",
        "table{border-collapse:collapse;width:100%;font-size:12px;margin-bottom:20px;}",
        "th,td{border:1px solid #cfd8dc;padding:4px 6px;}",
        "th{background:#eceff1;text-align:left;}",
        "tr:nth-child(even){background:#fafafa;}",
        "h1{font-size:20px;} h3{font-size:14px;margin-top:18px;}",
        ".meta{color:#607d8b;}",
        "</style></head><body>",
        "<h1>Signal Matrix</h1>",
        "<p class='meta'>Generated %s · %d messages · %s</p>"
        % (
            time.strftime("%Y-%m-%d %H:%M:%S"),
            len(db.messages),
            html_mod.escape(os.path.basename(db.path or "")),
        ),
    ]
    for cid, m in db.messages.items():
        parts.append(
            "<h3>%s (0x%X, DLC %d, %s)</h3>"
            % (html_mod.escape(m.name), cid, m.dlc, html_mod.escape(m.sender or ""))
        )
        if opts.get("comment") and m.comment:
            parts.append("<p>%s</p>" % html_mod.escape(m.comment))
        parts.append("<table><thead><tr>")
        cols = ["Signal", "Start", "Len", "Order", "Factor", "Offset", "Unit"]
        if opts.get("minmax"):
            cols += ["Min", "Max"]
        if opts.get("values"):
            cols.append("Values")
        if opts.get("comment"):
            cols.append("Comment")
        for col in cols:
            parts.append("<th>%s</th>" % col)
        parts.append("</tr></thead><tbody>")
        for s in m.signals:
            parts.append("<tr>")
            cells = [
                s.name,
                str(s.start_bit),
                str(s.bit_length),
                "Intel" if s.little_endian else "Motorola",
                str(s.factor),
                str(s.offset),
                s.unit or "",
            ]
            if opts.get("minmax"):
                cells += [str(s.minimum), str(s.maximum)]
            if opts.get("values"):
                cells.append(_val_table_str(s.value_table))
            if opts.get("comment"):
                cells.append(s.comment or "")
            for cell in cells:
                parts.append("<td>%s</td>" % html_mod.escape(str(cell)))
            parts.append("</tr>")
        parts.append("</tbody></table>")
    parts.append("</body></html>")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))


def format_meta(fmt_id: str) -> Optional[Tuple[str, str, str, str, str]]:
    for item in FORMATS:
        if item[0] == fmt_id:
            return item
    return None


def export_to_path(path: str, db, opts: dict, fmt_id: str) -> None:
    """Write matrix in *fmt_id* (see FORMATS). Raises ValueError if unknown."""
    if fmt_id == "csv":
        write_delimited(path, db, opts, delimiter=",", excel_bom=False)
    elif fmt_id == "excel-csv":
        write_delimited(path, db, opts, delimiter=",", excel_bom=True)
    elif fmt_id == "tsv":
        write_delimited(path, db, opts, delimiter="\t", excel_bom=False)
    elif fmt_id == "json":
        write_json(path, db, opts)
    elif fmt_id == "yaml":
        write_yaml(path, db, opts)
    elif fmt_id == "xml":
        write_xml(path, db, opts)
    elif fmt_id == "markdown":
        write_markdown(path, db, opts)
    elif fmt_id == "html":
        write_html(path, db, opts)
    else:
        raise ValueError("unknown export format: %s" % fmt_id)
