# -*- coding: utf-8 -*-
"""Minimal EDS/DCF parser for CANopen object dictionary sections.

Recognises [xxxx] / [xxxxsubN] sections and common keys:
ParameterName, ObjectType, DataType, AccessType, DefaultValue, PDOMapping.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


SECTION_RE = re.compile(
    r"^\[([0-9A-Fa-f]{1,4})(?:sub([0-9A-Fa-f]+))?\]\s*$", re.IGNORECASE
)
KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$")


@dataclass
class OdEntry:
    index: int
    subindex: int = 0
    name: str = ""
    object_type: str = ""
    data_type: str = ""
    access_type: str = ""
    default_value: str = ""
    pdo_mapping: str = ""
    extra: Dict[str, str] = field(default_factory=dict)

    @property
    def key(self) -> Tuple[int, int]:
        return (self.index, self.subindex)

    def display_index(self) -> str:
        if self.subindex:
            return "0x%04X:%02X" % (self.index, self.subindex)
        return "0x%04X" % self.index


def parse_eds(text: str) -> List[OdEntry]:
    """Parse EDS/DCF text into a list of OdEntry (sorted by index, subindex)."""
    entries: Dict[Tuple[int, int], OdEntry] = {}
    current: Optional[OdEntry] = None

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(";"):
            continue
        m = SECTION_RE.match(line)
        if m:
            idx = int(m.group(1), 16)
            sub = int(m.group(2), 16) if m.group(2) else 0
            # Skip FileInfo / DeviceInfo / Comments / MandatoryObjects etc.
            # Only keep numeric OD sections (0x1000+ typically; allow any hex).
            entry = OdEntry(index=idx, subindex=sub)
            entries[(idx, sub)] = entry
            current = entry
            continue
        if current is None:
            continue
        km = KEY_RE.match(line)
        if not km:
            continue
        key, val = km.group(1), km.group(2).strip()
        val = val.strip('"')
        kl = key.lower()
        if kl == "parametername":
            current.name = val
        elif kl == "objecttype":
            current.object_type = val
        elif kl == "datatype":
            current.data_type = val
        elif kl == "accesstype":
            current.access_type = val
        elif kl == "defaultvalue":
            current.default_value = val
        elif kl == "pdomapping":
            current.pdo_mapping = val
        else:
            current.extra[key] = val

    # Drop empty shell sections with no useful fields (optional keep all numeric)
    result = sorted(entries.values(), key=lambda e: (e.index, e.subindex))
    return result


def parse_eds_file(path: str) -> List[OdEntry]:
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return parse_eds(f.read())


def export_eds_text(
    entries: List[OdEntry],
    file_name: str = "export.eds",
    device_name: str = "CANopen Suite Export",
) -> str:
    """Serialize OD entries to a minimal EDS-like text."""
    lines = [
        "[FileInfo]",
        "FileName=%s" % file_name,
        "FileVersion=1",
        "FileRevision=0",
        "EDSVersion=4.0",
        "Description=Generated by CANopen Suite",
        "CreationDate=01-01-2026",
        "CreationTime=00:00AM",
        "CreatedBy=sin",
        "",
        "[DeviceInfo]",
        "VendorName=sin",
        "ProductName=%s" % device_name,
        "",
    ]
    # MandatoryObjects / OptionalObjects counts (simplified)
    indices = sorted({e.index for e in entries})
    lines.append("[MandatoryObjects]")
    lines.append("SupportedObjects=%d" % min(len(indices), 1))
    if indices:
        lines.append("1=0x%04X" % indices[0])
    lines.append("")

    for e in sorted(entries, key=lambda x: (x.index, x.subindex)):
        if e.subindex:
            lines.append("[%04Xsub%X]" % (e.index, e.subindex))
        else:
            lines.append("[%04X]" % e.index)
        if e.name:
            lines.append("ParameterName=%s" % e.name)
        if e.object_type:
            lines.append("ObjectType=%s" % e.object_type)
        if e.data_type:
            lines.append("DataType=%s" % e.data_type)
        if e.access_type:
            lines.append("AccessType=%s" % e.access_type)
        if e.default_value:
            lines.append("DefaultValue=%s" % e.default_value)
        if e.pdo_mapping:
            lines.append("PDOMapping=%s" % e.pdo_mapping)
        for k, v in sorted(e.extra.items()):
            lines.append("%s=%s" % (k, v))
        lines.append("")
    return "\n".join(lines)


def entries_to_dict(entries: List[OdEntry]) -> Dict[Tuple[int, int], OdEntry]:
    return {e.key: e for e in entries}


def find_entry(
    entries: List[OdEntry], index: int, subindex: int = 0
) -> Optional[OdEntry]:
    for e in entries:
        if e.index == index and e.subindex == subindex:
            return e
    return None
