# -*- coding: utf-8 -*-
"""Generate CanFestival-style Node.c / Node.h from an EdsDocument."""

from __future__ import annotations

from datetime import date
from typing import Dict, List, Tuple

from _shared.edsparse import EdsDocument, OdEntry

from .types import (
    access_cf,
    byte_size,
    cf_type,
    c_ident,
    ctype_info,
    group_by_index,
    is_var_entry,
    parse_default,
)


def _banner(doc: EdsDocument, node_name: str) -> str:
    path = doc.path or "(unsaved)"
    return "\n".join([
        "/*",
        " * CANopen object dictionary — CanFestival / objdictgen style",
        " * Generated by openbus canopen_codegen on %s" % date.today().isoformat(),
        " * Node: %s" % node_name,
        " * Source: %s" % path,
        " *",
        " * Compile with CanFestival (include data.h / objdictdef.h).",
        " * See canopen_codegen/stacks/README.md.",
        " */",
        "",
    ])


def _obj_symbol(node: str, index: int, sub: int) -> str:
    return "%s_obj%04X_%X" % (node, index, sub)


def _is_array(e: OdEntry) -> bool:
    info = ctype_info(e.data_type)
    return info.is_string or info.is_domain


def generate_h(doc: EdsDocument, node_name: str = "Node") -> str:
    name = c_ident(node_name, "Node")
    lines = [_banner(doc, name)]
    guard = "%s_H" % name.upper()
    lines += [
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "",
        '#include "data.h"',
        "",
        "extern const UNS16 %s_ObjdictSize;" % name,
        "extern const indextable %s_objdict[];" % name,
        "extern CO_Data %s_Data;" % name,
        "",
        "const indextable * %s_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, "
        "ODCallback_t **callbacks);" % name,
        "",
    ]
    for e in doc.entries:
        if not is_var_entry(e):
            continue
        cf = cf_type(e.data_type)
        sym = _obj_symbol(name, e.index, e.subindex)
        size = byte_size(e.data_type)
        if _is_array(e):
            lines.append(
                "extern UNS8 %s[%d]; /* 0x%04X:%02X %s */" % (
                    sym, size, e.index, e.subindex, e.name or ""))
        else:
            lines.append(
                "extern %s %s; /* 0x%04X:%02X %s */" % (
                    cf, sym, e.index, e.subindex, e.name or ""))
    lines += ["", "#endif /* %s */" % guard, ""]
    return "\n".join(lines)


def generate_c(doc: EdsDocument, node_name: str = "Node") -> str:
    name = c_ident(node_name, "Node")
    lines = [_banner(doc, name)]
    lines += [
        '#include "%s.h"' % name,
        '#include "objdictdef.h"',
        "",
    ]

    value_lines: List[str] = []
    count_lines: List[str] = []
    table_blocks: List[str] = []
    declare_rows: List[Tuple[int, str, int]] = []

    for idx, subs in group_by_index(doc.entries):
        var_subs = [e for e in subs if is_var_entry(e)]
        if not var_subs:
            continue
        have_zero = any(e.subindex == 0 for e in var_subs)
        arr_name = "%s_Index%04X" % (name, idx)

        for e in var_subs:
            cf = cf_type(e.data_type)
            sym = _obj_symbol(name, e.index, e.subindex)
            lit = parse_default(e.effective_value(), e.data_type)
            size = byte_size(e.data_type)
            if _is_array(e):
                value_lines.append(
                    "UNS8 %s[%d]; /* 0x%04X:%02X %s */" % (
                        sym, size, e.index, e.subindex, e.name or ""))
            elif lit.startswith('"'):
                value_lines.append("%s %s = 0;" % (cf, sym))
            else:
                value_lines.append(
                    "%s %s = (%s)%s;" % (cf, sym, cf, lit))

        rows: List[str] = []
        if not have_zero:
            max_sub = max(e.subindex for e in var_subs)
            count_sym = "%s_Index%04X_count" % (name, idx)
            count_lines.append(
                "static UNS8 %s = %d;" % (count_sym, max_sub))
            rows.append(
                "  { RO, UNS8, sizeof(UNS8), (void*)&%s }," % count_sym)

        for e in sorted(var_subs, key=lambda x: x.subindex):
            cf = cf_type(e.data_type)
            sym = _obj_symbol(name, e.index, e.subindex)
            acc = access_cf(e.access_type)
            if _is_array(e):
                rows.append(
                    "  { %s, UNS8, %d, (void*)%s }, /* %d %s */" % (
                        acc, byte_size(e.data_type), sym,
                        e.subindex, e.name or ""))
            else:
                rows.append(
                    "  { %s, %s, sizeof(%s), (void*)&%s }, /* %d %s */" % (
                        acc, cf, cf, sym, e.subindex, e.name or ""))

        table_blocks.append(
            "const subindex %s[] = {\n%s\n};\n" % (arr_name, "\n".join(rows)))
        declare_rows.append((idx, arr_name, len(rows)))

    lines.extend(value_lines)
    lines.append("")
    if count_lines:
        lines.extend(count_lines)
        lines.append("")
    lines.extend(table_blocks)

    lines.append("const indextable %s_objdict[] = {" % name)
    for idx, arr_name, n_subs in declare_rows:
        lines.append(
            "  { (subindex*)%s, %d, 0x%04X }," % (arr_name, n_subs, idx))
    if not declare_rows:
        lines.append("  { NULL, 0, 0 },")
    lines.append("};")
    lines.append("")
    lines.append(
        "const UNS16 %s_ObjdictSize = "
        "sizeof(%s_objdict)/sizeof(%s_objdict[0]);" % (name, name, name))
    lines.append("")
    lines.append(
        "const indextable * %s_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, "
        "ODCallback_t **callbacks)" % name)
    lines.append("{")
    lines.append("  int i;")
    lines.append("  *callbacks = NULL;")
    lines.append("  switch(wIndex){")
    for i, (idx, _a, _n) in enumerate(declare_rows):
        lines.append("    case 0x%04X: i = %d; break;" % (idx, i))
    lines.append("    default:")
    lines.append("      *errorCode = OD_NO_SUCH_OBJECT;")
    lines.append("      return NULL;")
    lines.append("  }")
    lines.append("  *errorCode = OD_SUCCESSFUL;")
    lines.append("  return &%s_objdict[i];" % name)
    lines.append("}")
    lines.append("")
    lines.append(
        "CO_Data %s_Data = CANOPEN_NODE_DATA_INITIALIZER(%s);" % (name, name))
    lines.append("")
    return "\n".join(lines)


def generate(doc: EdsDocument, node_name: str = "Node") -> Dict[str, str]:
    name = c_ident(node_name, "Node")
    return {
        "%s.h" % name: generate_h(doc, name),
        "%s.c" % name: generate_c(doc, name),
    }
